services:
  - type: web
    name: videoauthenticator
    env: python
    rootDir: videoauth
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn videoauth.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
