# Generated by Django 5.2.8 on 2026-08-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='authenticity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='forensic_report_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='metadata_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='noise_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='spatial_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='temporal_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Authentic', 'Authentic'), ('Suspicious', 'Suspicious'), ('Deepfake', 'Deepfake / AI-Generated'), ('Error', 'Analysis Failed')], default='Pending', max_length=30),
        ),
    ]
